#!/bin/bash
# Script to reload the GhydraMCP plugin in Ghidra

echo "======================================================================"
echo "GhydraMCP Plugin Reload Instructions"
echo "======================================================================"
echo ""
echo "The plugin has been rebuilt with the writable fix."
echo "To apply the changes, you need to:"
echo ""
echo "1. In Ghidra, go to File -> Configure -> Extensions"
echo "2. Find 'GhydraMCP' in the list"
echo "3. Click 'Remove' to uninstall the old version"
echo "4. Click 'Add Extension File' and select:"
echo "   /home/eljakim/Source/GhydraMCP/target/GhydraMCP-Complete-d045f91-20260514-151343.zip"
echo "5. Click 'OK' to install the new version"
echo "6. Restart Ghidra"
echo ""
echo "Alternatively, you can:"
echo "1. Close Ghidra"
echo "2. Copy the new plugin to your Ghidra extensions directory:"
echo "   cp /home/eljakim/Source/GhydraMCP/target/GhydraMCP-Complete-d045f91-20260514-151343.zip \\"
echo "     ~/.ghidra/.ghidra_*/Extensions/GhydraMCP.zip"
echo "3. Restart Ghidra"
echo ""
echo "======================================================================"
echo "After reloading, run: python3 test_memory_writable.py"
echo "======================================================================"